//CI/CD pipeline for a website that deploys code to an AWS EC2 instance using Jenkins. 
pipeline {
    agent any

    stages {
        stage('Featch_Code') {
            steps {
                //Fetching code from remote repository
                git 'https://github.com/SkyrunnerOO7/Test_Web_Site'
            }
        }

        stage('Deploy') {
            steps {
                //installing apache2 to run the website
                sh 'sudo apt-get install apache2 -y'
                //staring the apache2
                sh 'sudo systemctl start apache2'
                //enabling the apache2
                sh 'sudo systemctl enable apache2'
                
                //Copying the content of the code fetch form repository to host the site on ec2
                sh 'sudo cp -r /var/lib/jenkins/workspace/test/* /var/www/html/'
                //After that Restarting the apache2 service
                sh 'sudo systemctl restart apache2'
            }
        }
    }
}
